mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gvb_db
  user: root
  password: root
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 3001
  env: release
site_info:
  created_at: "2023-09-15"
  bei_an: 湘ICP备2021010654号-3
  title: 枫枫知道
  qq_image: /uploads/file/admin/qq_20230930151442.png
  version: 8.0.1
  email: 2663456523@qq.com
  wechat_image: /uploads/file/admin/wechat_20230930151521.png
  name: 枫枫知道
  job: 后端开发
  addr: 湖南长沙
  slogan: 枫枫知道
  slogan_en: FFENGZHIDAO
  web: http://www.fengfengzhidao.com/
  bilibili_url: https://space.bilibili.com/359151217
  gitee_url: https://gitee.com/fengfengzhidao
  github_url: https://github.com/fengfengzhidao/
upload:
  size: 2
  path: uploads/file
qq:
  app_id: '******'
  key: '******'
  redirect: http://blog.fengfengzhidao.com/login?flag=qq
qi_niu:
  enable: true
  access_key: '******'
  secret_key: '******'
  bucket: fengfengzhidao
  cdn: http://image.fengfengzhidao.com/
  zone: z2
  prefix: "1001"
  size: 6
email:
  host: smtp.qq.com
  port: 465
  user: '******'
  password: '******'
  default_from_email: 枫枫知道
  use_ssl: true
  user_tls: false
jwt:
  secret: '******'
  expires: 20
  issuer: "1234"
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
chat_group:
  isAnonymous: true
  isShowTime: false
  defaultLimit: 50
  contentLength: 101
  welcomeTitle: 枫枫知道在线聊天室
  isOnlinePeople: true
  isSendImage: true
  isSendFile: false
  isMd: true
gaode:
  enable: true
  key: '******'
