mysql:
  host: 127.0.0.1
  port: 3306
  config: charset=utf8mb4&parseTime=True&loc=Local
  db: gvb_db
  user: root
  password: "123456"
  log_level: dev
logger:
  level: info
  prefix: '[gvb]'
  director: log
  show_line: true
  log_in_console: true
system:
  host: 0.0.0.0
  port: 3333
  env: release
site_info:
  created_at: "2024-01-01"
  bei_an: 你的备案号
  title: 与蜗牛漫步
  qq_image: /uploads/file/Gopher/qq_20240108221653.jpg
  version: 2.0.0
  email: 你的邮箱
  wechat_image: /uploads/file/Gopher/wechat_20240108221659.jpg
  name: 与蜗牛漫步
  job: 全栈开发
  addr: 地址
  slogan: 个人博客
  slogan_en: GOPHERBLOG
  web: 博客地址
  csdn_url: CSDN 地址
  gitee_url: Gitee地址
  github_url: GitHub地址
upload:
  size: 6
  path: uploads/file
qq:
  app_id: "appID"
  key: "appKey"
  redirect: "回调地址"
qi_niu:
  enable: true
  access_key: "accessKey"
  secret_key: "secretKey"
  bucket: "bucket名"
  cdn: "CDN加速域名"
  zone: 地区
  prefix: 前缀
  size: 6 # 最大上传图片大小，单位 M
email:
  host: smtp.qq.com
  port: 465
  user: 邮箱
  password: 授权码
  default_from_email: GopherBlog
  use_ssl: true
  user_tls: false
jwt:
  secret: '******'
  expires: 240
  issuer: 颁发人，随便填
redis:
  ip: 127.0.0.1
  port: 6379
  password: ""
  pool_size: 100
es:
  host: http://127.0.0.1
  port: 9200
  user: ""
  password: ""
chat_group:
  isAnonymous: true
  isShowTime: false
  defaultLimit: 50
  contentLength: 101
  welcomeTitle: 在线聊天室
  isOnlinePeople: true
  isSendImage: true
  isSendFile: true
  isMd: true
gaode:
  enable: true
  key: 高德对应的key
big_model:
  setting:
    name: "qwen" # eg. qwen -> 通义千问
    enable: true # 是否启用
    order: 0
    title: GopherModel
    prompt: "" # 加强提示词
    slogan: "让更多人用上大模型"
    access_key_id: ""
    access_key_secret: ""
    agent_key: ""
    app_id: ""
  model_list:
    - label: 通义千问
      value: qwen
      disabled: false
    - label: 文心一言
      value: wenxin
      disabled: true
    - label: 星火大模型
      value: xinhuo
      disabled: true
    - label: 天工大模型
      value: tiangong
      disabled: true
    - label: ChatGPT
      value: chatgpt
      disabled: true
  session_setting: # 会话
    chat_scope:
    session_scope:
    day_scope:

